export const LOAD_CATAGORY_ITEM = 'LOAD_CATAGORY_ITEM';
export const FETCH_INDEX_POST = 'FETCH_INDEX_POST';
export const PUSH_REQUESTED_PAGE = 'PUSH_REQUESTED_PAGE';
export const PAGE_INCREMENT = 'PAGE_INCREMENT';
export const CODE_PAGE_INCREMENT = 'CODE_PAGE_INCREMENT';
export const NO_ANY_POSTS = 'NO_ANY_POSTS';
export const HIDDEN_INDEX_LOADING = 'HIDDEN_INDEX_LOADING';
export const CHANGE_BTN_VALUE = 'CHANGE_BTN_VALUE';
export const NO_MORE_CODE_DATA = 'NO_MORE_CODE_DATA';

export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_URL = 'CHANGE_URL';
